name: "Main Workflow"

on:
  push:
    branches:
      - "**"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Grab the code
        uses: actions/checkout@v4 #fetches the latest from github
      - name: Set up Node js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Transpile the code
        run: npm run build
      - name: Cashe the build files
        uses: actions/cache@v4
        with:
          path: build
          key: ({{ runner.os })-build-${{ github.sha }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Grab the code
        uses: actions/checkout@v4 #fetches the latest from github

      - name: Set up Node js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Cashe the build files
        uses: actions/cache@v4
        with:
          path: coverage
          key: ({{ runner.os })-build-${{ github.sha }}
      
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Grab the code
        uses: actions/checkout@v4 #fetches the latest from github

      - name: Set up Node js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
  release:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Grab the code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package build
        run: |
         cd build
         zip -r ../artifact.zip .

      - name: Version Bump
        id: version
        uses: phips28/gh-action-bump-version@master
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'MAJOR'
          minor-wording: 'minor'
          patch-wording: 'patch,fixes'
          commit-message: 'CI: Bump Version to {{version}} [skip ci]'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifact.zip
          tag_name: ${{ steps.version.outputs.newTag }}
          draft: false
          prerelease: false
          make_latest: true
          overwrite_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



           
         